############## LIRUDY 2011 ##############################
MODEL_FILE_CPU="li_rudy_2011.c"
MODEL_FILE_GPU="li_rudy_2011.cu"
MODEL_FILE_SYCL=""
COMMON_HEADERS="li_rudy_2011.h"

COMPILE_MODEL_LIB "li_rudy_2011" "$MODEL_FILE_CPU" "$MODEL_FILE_GPU" "$MODEL_FILE_SYCL" "$COMMON_HEADERS"