#ifndef MONOALG3D_GUI_SHADERS_H
#define MONOALG3D_GUI_SHADERS_H

// Embedded GLSL sources: no runtime shader file lookup is required.

// Source: res/instanced_vertex_shader.vs
static const char gui_instanced_vertex_shader[] =
    "#version 330\n"
    "\n"
    "// Input vertex attributes\n"
    "in vec3 vertexPosition;\n"
    "in vec2 vertexTexCoord;\n"
    "in vec3 vertexNormal;\n"
    "in vec4 vertexColor;\n"
    "\n"
    "in mat4 instanceTransform;\n"
    "\n"
    "// Input uniform values\n"
    "uniform mat4 mvp;\n"
    "uniform mat4 matNormal;\n"
    "uniform int dgrid;\n"
    "\n"
    "// Output vertex attributes (to fragment shader)\n"
    "out vec3 fragPosition;\n"
    "out vec2 fragTexCoord;\n"
    "out vec4 fragColor;\n"
    "out vec3 fragNormal;\n"
    "flat out int drawGrid;\n"
    "\n"
    "// NOTE: Add here your custom variables\n"
    "in vec4 color;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    // Compute MVP for current instance\n"
    "    mat4 mvpi = mvp*instanceTransform;\n"
    "\n"
    "    // Send vertex attributes to fragment shader\n"
    "    fragPosition = vec3(mvpi*vec4(vertexPosition, 1.0));\n"
    "    fragTexCoord = vertexTexCoord;\n"
    "    fragColor = color;\n"
    "    fragNormal = normalize(vec3(matNormal*vec4(vertexNormal, 1.0)));\n"
    "\n"
    "    drawGrid = dgrid;\n"
    "\n"
    "    // Calculate final vertex position\n"
    "    gl_Position = mvpi*vec4(vertexPosition, 1.0);\n"
    "}\n"
    "\n"
    ;

// Source: res/fragment_shader.fs
static const char gui_fragment_shader[] =
    "#version 330\n"
    "\n"
    "in vec2 fragTexCoord;\n"
    "in vec4 fragColor;\n"
    "in vec3 fragNormal;\n"
    "in vec3 fragPosition;\n"
    "\n"
    "flat in int drawGrid;\n"
    "\n"
    "out vec4 finalColor;\n"
    "\n"
    "const float offset = 1.0 / 20.0;\n"
    "const float one_minus_offset = 1.0 - offset;\n"
    "const vec4 pink = vec4(1, 0.46, 1, 1.0);\n"
    "const float ambientStrength = 0.1;\n"
    "\n"
    "struct Light {\n"
    "    int enabled;\n"
    "    int type;\n"
    "    vec3 position;\n"
    "    vec3 target;\n"
    "    vec4 color;\n"
    "};\n"
    "\n"
    "// Input lighting values\n"
    "uniform Light lights[1];\n"
    "\n"
    "void main() {\n"
    "\n"
    "    vec3 lightDot = vec3(0.0);\n"
    "    vec3 normal = normalize(fragNormal);\n"
    "    vec3 ambient = vec3(1.0);\n"
    "\n"
    "    vec3 lp = lights[0].position;\n"
    "    vec3 lt = lights[0].target;\n"
    "    vec4 lc = lights[0].color;\n"
    "\n"
    "    vec3 light = vec3(0.0);\n"
    "    light = -normalize(lt - lp);\n"
    "    float NdotL = max(dot(normal, light), 0.0);\n"
    "    lightDot += lc.rgb * NdotL;\n"
    "    ambient = ambientStrength * lc.rgb;\n"
    "\n"
    "    bool draw_countour = fragTexCoord.x < offset || fragTexCoord.y < offset || fragTexCoord.x > one_minus_offset || fragTexCoord.y > one_minus_offset;\n"
    "    bool selected = (fragColor.a == 0);\n"
    "\n"
    "    finalColor = fragColor;\n"
    "\n"
    "    if(drawGrid == 0) {\n"
    "        if(selected) {\n"
    "            if(draw_countour) {\n"
    "                finalColor = pink;\n"
    "            } else {\n"
    "                finalColor = vec4(fragColor.rgb, 1);\n"
    "            }\n"
    "        } else {\n"
    "            finalColor = fragColor;\n"
    "        }\n"
    "    } else if(drawGrid == 1) {\n"
    "        if(draw_countour) {\n"
    "            if(selected) {\n"
    "                finalColor = pink;\n"
    "            } else {\n"
    "                finalColor = vec4(0,0,0,1);\n"
    "            }\n"
    "        }\n"
    "        else {\n"
    "            if(selected) {\n"
    "                finalColor = vec4(fragColor.rgb, 1);\n"
    "            } else {\n"
    "                finalColor = fragColor;\n"
    "            }\n"
    "        }\n"
    "    } else if(drawGrid == 2) {\n"
    "        if(draw_countour) {\n"
    "            if(selected) {\n"
    "                finalColor = pink;\n"
    "            }\n"
    "            else {\n"
    "                finalColor = fragColor;\n"
    "            }\n"
    "        }\n"
    "        else {\n"
    "            finalColor = vec4(0,0,0,0);\n"
    "        }\n"
    "    }\n"
    "\n"
    "    vec3 result = (ambient + lightDot) * finalColor.rgb;\n"
    "    finalColor = vec4(result, finalColor.a);\n"
    "}\n"
    "\n"
    "\n"
    ;

#endif // MONOALG3D_GUI_SHADERS_H
