GPU_UTILS_SOURCE_FILES="gpu_utils.c"
GPU_UTILS_HEADER_FILES="gpu_utils.h"

if [ -n "$CUDA_FOUND" ]; then
    GPU_UTILS_EXTRA_LIB_PATH=$CUDA_LIBRARY_PATH
    GPU_UTILS_DYNAMIC_LIBS="c cudart"
    GPU_UTILS_SOURCE_FILES="$GPU_UTILS_SOURCE_FILES gpu_utils.cu"
fi


COMPILE_SHARED_LIB "gpu_utils" "$GPU_UTILS_SOURCE_FILES" "$GPU_UTILS_HEADER_FILES" "" "$GPU_UTILS_DYNAMIC_LIBS" "$GPU_UTILS_EXTRA_LIB_PATH" "" "$CUDA_FOUND"
#COMPILE_STATIC_LIB "gpu_utils" "$GPU_UTILS_SOURCE_FILES" "$GPU_UTILS_HEADER_FILES"
