# ===========================================================================
# Author: Lucas Berg
# Description: Simple simulation to test the Tworld model with a cable.
# ============================================================================
[main]
num_threads=8
dt_pde=0.005
simulation_time=500.0
abort_on_no_activity=false
use_adaptivity=false

[update_monodomain]
main_function=update_monodomain_default

[save_result]
print_rate=200
output_dir=./outputs/cable_Tworld_endo_baseline_cpu_en
add_timestamp=false
binary=true
main_function=save_as_ensight
remove_older_simulation=true

;[save_result]
;print_rate=1
;output_dir=./outputs/cable_ToRORd_Land_endo_baseline_cpu
;file_name=./outputs/cable_ToRORd_Land_endo_baseline_cpu/full_trace_first_cell_endo.txt
;output_dir=./outputs/cable_ToRORd_Land_mid_baseline_cpu
;file_name=./outputs/cable_ToRORd_Land_mid_baseline_cpu/full_trace_first_cell_mid.txt
;output_dir=./outputs/cable_ToRORd_Land_epi_baseline_cpu
;file_name=./outputs/cable_ToRORd_Land_epi_baseline_cpu/full_trace_first_cell_epi.txt
;main_function=save_one_cell_state_variables
;init_function=init_save_one_cell_state_variables
;end_function=end_save_one_cell_state_variables
;cell_center_x=50
;cell_center_y=50
;cell_center_z=50
;remove_older_simulation=true

[assembly_matrix]
init_function=set_initial_conditions_fvm
sigma_x=0.000176
sigma_y=0.000176
sigma_z=0.000176
library_file=shared_libs/libdefault_matrix_assembly.so
main_function=homogeneous_sigma_assembly_matrix

[linear_system_solver]
tolerance=1e-16
use_preconditioner=no
max_iterations=500
library_file=shared_libs/libdefault_linear_system_solver.so
use_gpu=no
main_function=conjugate_gradient
init_function=init_conjugate_gradient
end_function=end_conjugate_gradient

[domain]
name=Cable Mesh with no fibrosis
start_dx=100.0
start_dy=100.0
start_dz=100.0
cable_length=21000.0
main_function=initialize_grid_with_cable_mesh

; Solving using Adaptive Euler
;[ode_solver]
;adaptive=true
;reltol=1e-9
;abstol=1e-9
;use_gpu=no
;gpu_id=0
;library_file= shared_libs/libTworld.so

; Rush-Larsen
[ode_solver]
adaptive=false
dt=0.005
use_gpu=no
gpu_id=0
library_file= shared_libs/libTworld.so

[stim_plain]
start = 0.0
duration = 1.0
period = 1000.0
current = -53.0
x_limit = 500.0
main_function = stim_if_x_less_than
