# ----------------------------------------------------------------------------------------------------
# Author: Lucas Berg
# Script to check if a given cell achieved steady-state
# ----------------------------------------------------------------------------------------------------

import sys
import numpy as np
import matplotlib.pyplot as plt

def read_transmembrane_potential(input_file, dt, print_rate):
    data = np.genfromtxt(input_file)
    n = len(data)
    ms_each_step = dt*print_rate

    end_simulation = (n-1) * ms_each_step

    timesteps = np.arange(0,n)*ms_each_step
    vms = data

    return timesteps, vms


def check_steady_state (t,vm,dt,print_rate,bcl):

    tolerance = 1.0e-04
    offset = int( (bcl / dt) / print_rate)
    max_num_timesteps = len(t)
    num_aps = max_num_timesteps / offset

    cur_index = 0
    prev_index = 0
    for i in range(num_aps):
        prev_index = cur_index
        cur_index = i*offset

        prev_vm = vm[prev_index]
        cur_vm = vm[cur_index]

        if (i != 0):
            error = abs((cur_vm-prev_vm)/prev_vm)
            print("Current = %g -- Previous = %g -- Error = %g" % (cur_vm,prev_vm,error))
    
    if (error < tolerance):
        return True
    else:
        return False

def main():
	
    if len(sys.argv) != 5:
        print("---------------------------------------------------------------------------------------------------------------------")
        print("Usage:> python %s <input_file_1> <dt> <print_rate> <bcl>" % sys.argv[0])
        print("---------------------------------------------------------------------------------------------------------------------")
        print("<input_file_1> = Input file with the AP")
        print("<dt> = Timestep value used for the simulation")
        print("<print_rate> = Print rate used for the simulation")
        print("<num_aps> = Number of AP`s generated by the simulation")
        print("---------------------------------------------------------------------------------------------------------------------")
        print("Example:> python %s aps/cell-6240-sc0.txt 0.02 50 400" % (sys.argv[0]))
        print("---------------------------------------------------------------------------------------------------------------------")
        return 1

    input_file_1 = sys.argv[1]
    dt = float(sys.argv[2])
    print_rate = int(sys.argv[3])
    bcl = int(sys.argv[4])

    t1, vm1 = read_transmembrane_potential(input_file_1,dt,print_rate)

    ok = check_steady_state(t1,vm1,dt,print_rate,bcl)

    if (ok == True):
        print("[+] Steady-state was reached!")
    else:
        print("[-] ERROR! Steady-state was NOT reached!")

if __name__ == "__main__":
    main()
